### ISSUE TITLE
Update augeasproviders_core, pam and grub to puppet modules in metadata and fixtures

### ISSUE THREAD

**Issue by canihavethisone** [tom-krieger/cis_security_hardening#11]
The following modules have been transferred from herculesteam to puppet.  i suspect other augeas modules will soon do the same.  These appear 100% compatible as they simply changed publisher:

- puppet-augeasproviders_pam
- puppet-augeasproviders_core
- puppet-augeasproviders_grub

If you prefer I can create a pull request for this and the other issue I raised, though they are only changes in metadata and fixtures.

**Comment by tom-krieger** [comment]
I'm currently testing a new release with Redhat 7/8 STIG included. I can include this- Is not to much effort. But thanks for offering the pull request.

**Comment by tom-krieger** [comment]
Included in v0.7.2
