### ISSUE TITLE
purplehazech-syslogng is locked to stdlib 4.x and very old module

### ISSUE THREAD

**Issue by canihavethisone** [tom-krieger/cis_security_hardening#12]
`purplehazech-syslogng` hasn't been updated sine January 2015 and is locked to stdlib v4.x, making it impossible to install as other dependencies have higher version requirement for stdlib.

This should be removed or replaced if functionality is required

**Comment by tom-krieger** [comment]
syslog-ng will be removed with the next release.

**Comment by tom-krieger** [comment]
Included in v0.7.2 -> syslog-ng module removed.
