### ISSUE TITLE
hiera.yaml does not detect operating system correctly

### ISSUE THREAD

**Issue by parryb** [tom-krieger/cis_security_hardening#13]
hiera.yaml should have operating system detection through the use of facts to correctly determine the hierarchy of the params and rule datasets. I would suggest using the fact os.family or os.name.

i.e. AlamaLinux ~ RedHat so you would use os.family but could use os.name if you wanted separate them out?

**Comment by tom-krieger** [comment]
CIS benchmarks are different for each OS and even for each OS version. I check what can be done.

**Comment by tom-krieger** [comment]
Fixed with v0.7.7
