### ISSUE TITLE
Errors found after running CIS-CAT evaluation tool against RHEL 8 build

### ISSUE THREAD

**Issue by parryb** [tom-krieger/cis_security_hardening#32]
Tom,

I've run CIS-CAT tool against a RHEL8.6 VM it throws up a few errors against CIS lock down specification.  I'll create a few pull requests to fix and update this ticket with explanation of fixes.

I can't share the results with you as it's on my secure network.

**Comment by tom-krieger** [comment]
Parry,

just remove all data related to your secure environment and let me know the problems you found. You can definitely tell me which CIS benchmark rules are violated and what the problem is.

**Comment by tom-krieger** [comment]
Closed due to inactivity
