### ISSUE TITLE
auditd - Record Information on Kernel Modules Loading and Unloading missing 32-bit

### ISSUE THREAD

**Issue by warrenbel** [tom-krieger/cis_security_hardening#69]
I am failing this rule:
# init_module,finit_module,delete_module,create_module,query_module
  class { 'cis_security_hardening::rules::auditd_kernel_modules':
    enforce => true,
  }

-a always,exit -F arch=b64 -S init_module,finit_module,delete_module,create_module,query_module -F auid>=1000 -F auid!=4294967295 -k kernel_modules

it is failing because no for 32bit.
I can use the auditd_init_module and  auditd_delete_module,  but it has no own classes for create, finit, and query.

**Comment by tom-krieger** [comment]
The CIS benchmark for RHEL 8 does not mention a 32 bit rule in version 2.0.0 and 3.0.0. Maybe your scanner is wrong?

**Comment by tom-krieger** [comment]
Any news on that or can we close this issue?

**Comment by tom-krieger** [comment]
As there is no new information I close this now
