### ISSUE TITLE
auditd_user_emulation failing

### ISSUE THREAD

**Issue by warrenbel** [tom-krieger/cis_security_hardening#70]
I am getting a fail on this rule: using Openscap Red Hat Enterprise Linux 8 Benchmark™, v2.0.0

  class { 'cis_security_hardening::rules::auditd_user_emulation':
    enforce => true,
  }

Result:
-a always,exit -F arch=b32 -C euid!=uid -F auid!=unset -S execve -k user_emulation
-a always,exit -F arch=b64 -C euid!=uid -F auid!=unset -S execve -k user_emulation

But it is passing if i change to this format:
-a always,exit -F arch=b32 -S execve -C euid!=uid -F auid!=unset -k user_emulation
-a always,exit -F arch=b64 -S execve -C euid!=uid -F auid!=unset -k user_emulation

Maybe it is just the way they construct their search pattern.

**Comment by tom-krieger** [comment]
That is a problem of the scanner in my opinion but  will reorder the options.

**Comment by tom-krieger** [comment]
Will be fixed in upcoming release.
