### ISSUE TITLE
umask_setting.pp makes pam changes even if authselect::enforce is set to false

### ISSUE THREAD

**Issue by landrypm** [tom-krieger/cis_security_hardening#76]
While I am using cis_security_hardening for most tasks I do still rely on other puppet modules for other tasks. On my system I use a separate module to manage authselect configuration.  I have 

> cis_security_hardening::rules::authselect::enforce:    false

in my params file but umask_setting.pp still attempts to make changes to pam.d files.

I solved the issue by enclosing the 

> $services.each |$srv| {

loop in umask_setting.pp within a if clause:

```
$authselect_enforce = fact('cis_security_hardening.authselect.enforce')
if $authselect_enforce {
       $services.each |$srv| {
       ...
       }
}

```

**Comment by tom-krieger** [comment]
I include this in version v0.9.2 but in a slightlt different way.

**Comment by landrypm** [comment]
Thanks

--
Patrick Landry
________________________________
