### ISSUE TITLE
no license set on the repo

### ISSUE THREAD

**Issue by bwitt** [tom-krieger/cis_security_hardening#84]
I notice there's no license set on the repo; however, [the README](https://github.com/tom-krieger/cis_security_hardening/blob/main/README.md#warranty) and [metadata file](https://github.com/tom-krieger/cis_security_hardening/blob/237379891a2f5f2fc793def1d06db5a68edb98cd/metadata.json#L6) refer to Apache 2.0.  

Could you also set it in the repo so it's clear?  That would mean putting a `LICENSE.txt` (or similar) file in the repo.

**Comment by tom-krieger** [comment]
I close this issue as I accepted your PR and merged it into my Debian 12 branch.

**Comment by bwitt** [comment]
> I close this issue as I accepted your PR and merged it into my Debian 12 branch.

Thanks! Will it get merged to `main` at some point?  What's the process?
