### ISSUE TITLE
need puppetlabs-firewall bug fix in 8.0.3 (support puppetlabs-firewall < 9.0.0 ?)

### ISSUE THREAD

**Issue by bwitt** [tom-krieger/cis_security_hardening#87]
I am trying to use this module but am running [into this issue in puppetlabs-firewall which is fixed in v8.0.3](https://github.com/puppetlabs/puppetlabs-firewall/issues/1162); this module only allows [puppetlabs-firewall >= 7.0.0 < 8.0.0](https://github.com/tom-krieger/cis_security_hardening/blob/237379891a2f5f2fc793def1d06db5a68edb98cd/metadata.json#L57).

**Comment by rootshellz** [comment]
https://github.com/tom-krieger/cis_security_hardening/pull/88

**Comment by tom-krieger** [comment]
PR #88 merged. Will be in next release.
