### ISSUE TITLE
Release 0.9.6 on forge but no tag on github

### ISSUE THREAD

**Issue by bwitt** [tom-krieger/cis_security_hardening#91]
I see there's a version `0.9.6` [on the forge](https://forge.puppet.com/modules/tomkrieger/cis_security_hardening/readme)  (thanks!)

But I don't see [such a tag on github](https://github.com/tom-krieger/cis_security_hardening/tags); would you be able to tag the commit used for 0.9.6?

**Comment by tom-krieger** [comment]
done
